config/routes.rb
Rails.application.routes.draw do
  
  devise_for :admins, controllers: {
      sessions: 'admins/sessions'
      }
    
  devise_for :usuarios, controllers: {
        sessions: 'usuarios/sessions'
      }
    
  resources :zombies do
      resources :brains
  end
    
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    
    root to: 'zombies#index'
    #root to: 'admins#sign_up'
    
    devise_scope :admin do
        #get = ruta que se quiera escribir
        get "admins/usuarios/list",
        to: "admins/sessions#list",
        as: "usuarios_list"
    end
    
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Zombies" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>

  <div class="top-bar">
      <div class="top-bar-left">
          <ul class="dropdown menu" data-dropdown-menu>             
             <% if usuario_signed_in? %>
              <li class="menu-text">                 
                  <a href="#">Navegando Zombies</a>
                  <ul class="menu">
                      <li><%= link_to "Índice de Zombies", zombies_path %></li>
                      
                      <% if ["editor", "contribuidor", nil].include? current_usuario.rol %>
                          <li><%= link_to "Nuevo Zombie", new_zombie_path %></li>
                      <% end %>
                  </ul>
              </li>
          </ul>
      </div>
      
      <div class="top-bar-right">
        <ul class="menu">
          <li>Bienvenid@ <%= current_usuario.email%></li>
          <li><%= link_to "Editar perfil", edit_usuario_registration_path %></li>
          <li><%= link_to "Cerrar Sesión", destroy_usuario_session_path, method: :delete %></li>
          
          <% elsif admin_signed_in? %>
          
          <li class="menu-text">                 
                  <a href="#">Navegando Zombies</a>
                  <ul class="menu">
                      <li><%= link_to "Índice de Zombies", zombies_path %></li>             
                          <li><%= link_to "Nuevo Zombie", new_zombie_path %></li>   
                  </ul>
              </li>
          </ul>
      </div>
      
      <div class="top-bar-right">
        <ul class="menu">
          <li>Bienvenid@ Admin <%= current_admin.nombre%></li>          
          <li><%= link_to "Cerrar Sesión", destroy_admin_session_path, method: :delete %></li>
                    
         <% else %>
          
          <li>¡REGISTRAR HOY!</li>
          <li><%= link_to "Iniciar Sesión", new_usuario_session_path %></li>
          <li><%= link_to "Registro", new_usuario_registration_path %></li>
          
         <% end %>
          
          </ul>  
      </div>
  </div>
  
    <% if notice %>
        <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
        <p class="alert alert-danger"><%= alert%></p>
    <% end %>
   
    <%= yield %>

  </body>
</html>